FROM python:3.11-slim

WORKDIR /app

COPY requirements-agent.txt .
RUN pip install --no-cache-dir -r requirements-agent.txt

COPY src/ src/
COPY prompts/ prompts/

# Hackathon injects nothing at runtime — bake credentials and models at build time
# (Track 2: "use your own credentials inside the container")
ARG FIREWORKS_API_KEY
ARG GOOGLE_API_KEY=""
ARG VISION_MODEL=accounts/fireworks/models/kimi-k2p6
ARG VISION_ALT_MODEL=""
ARG VISION_FALLBACK_MODEL=accounts/fireworks/models/minimax-m3
ARG CAPTION_MODEL=accounts/fireworks/models/deepseek-v4-flash

ENV FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}
ENV VISION_MODEL=${VISION_MODEL}
ENV VISION_ALT_MODEL=${VISION_ALT_MODEL}
ENV VISION_FALLBACK_MODEL=${VISION_FALLBACK_MODEL}
ENV CAPTION_MODEL=${CAPTION_MODEL}
# Single DeepSeek sample (best-of-2 doubles caption latency under the 10-min cap)
ENV CAPTION_MODEL_POOL=deepseek-v4-flash
ENV DESCRIBE_DUAL=0
ENV PYTHONUNBUFFERED=1
ENV PARALLEL_STYLES=1
ENV OVERLAP_PIPELINE=1
ENV PREFETCH_DEPTH=2
ENV STRUCTURED_DESCRIBE=1
ENV DOWNLOAD_READ_TIMEOUT=90
ENV DESCRIBE_MAX_TOKENS=1200
ENV DESCRIBE_TEMPERATURE=0.2
ENV GOOGLE_DESCRIBE_MAX_TOKENS=1024
ENV GOOGLE_API_TIMEOUT_S=30
ENV STYLE_MAX_TOKENS=400
ENV FRAME_MODE=scene
ENV FRAME_SCENE_SAMPLE_S=1.0
ENV FRAME_INTERVAL_S=4
ENV FRAME_COUNT_MIN=8
ENV FRAME_COUNT_MAX=12
ENV FRAME_WIDTH=384
ENV API_TIMEOUT_S=60
ENV DESCRIBE_MAX_ATTEMPTS=2
ENV DESCRIBE_MAX_ATTEMPTS_WITH_FALLBACK=1
ENV DESCRIBE_QUALITY_GATE=1
ENV DESCRIBE_LONG_DURATION_S=60
# Prefer MiniMax on very long clips to keep multimodal payload/time down
ENV DESCRIBE_LONG_SKIP_PRIMARY_S=90
ENV FRAME_LONG_DURATION_S=60
ENV FRAME_LONG_INTERVAL_S=4
ENV FRAME_LONG_COUNT_MIN=10
ENV FRAME_LONG_COUNT_MAX=14
ENV STYLE_MAX_ATTEMPTS=3
ENV STYLE_META_LEAK_SALVAGE=1
ENV STYLE_JSON_MODE=1
ENV STYLE_COMPRESS_ON_LONG=1
ENV TIME_BUDGET_S=520
ENV DEADLINE_RESERVE_S=35
ENV JUDGE_RETRY=1
ENV JUDGE_RETRY_RESERVE_S=25
ENV JUDGE_RETRY_REGEX=1
ENV JUDGE_RETRY_DIVERSITY=1
ENV JUDGE_RETRY_MAX_PER_STYLE=1
ENV CAPTION_POOL_TEMP_DELTA=0.15
ENV CAPTION_JUDGE_TIEBREAK=1
ENV CAPTION_TIEBREAK_MARGIN=8
ENV JUDGE_MODEL=accounts/fireworks/models/gpt-oss-120b
ENV JUDGE_MIN_SCORE=0.9
ENV JUDGE_RETRY_QUALITY_MIN=0.9
ENV JUDGE_MIN_REMAINING_S=140
ENV JUDGE_SKIP_DISTINCTNESS=1
ENV JUDGE_PARALLEL_STYLES=1
ENV JUDGE_SLEEP_MS=0
ENV CAPTION_VISION_ACCURACY=0
ENV CAPTION_VISION_JUDGE_MODEL=accounts/fireworks/models/minimax-m3
ENV FRIENDLY_FAILURES=1

# Container reads /input/tasks.json and writes /output/results.json
ENTRYPOINT ["python", "-m", "src.main"]
